### ISSUE TITLE
Webpack:: Cannot find Module

### ISSUE THREAD

**Issue by allencoded** [froala/aurelia-froala-editor#33]
Following the instructions I am getting the following console errors:

`Error: Cannot find module './aurelia-froala-editor/froala-editor'.`

`Uncaught (in promise) Error: Cannot find module './aurelia-froala-editor/froala-editor'.`

in main.js I have:

```import * as froala from 'froala-editor/js/froala_editor.pkgd.min.js';
import 'froala-editor/css/froala_editor.pkgd.min.css';

.plugin('aurelia-froala-editor')
```

I am using the latest webpack beta 2 version as well as all the latest versions from Aurelia.

**Comment by hmarcelodn** [comment]
Same issue is happening to me:

http://stackoverflow.com/questions/43191885/skeleton-plugin-module-not-found-issue-after-build

**Comment by wjbarber3** [comment]
I am having this same issue. Any help here?

**Comment by stefanneculai** [comment]
@wjbarber3 please update the plugin and follow: https://github.com/froala/aurelia-froala-editor#with-webpack.

**Comment by sboyd** [comment]
hi @stefanneculai the issue that @wjbarber3 and I are running into has to do with the fact that the version of the skeleton, which is https://github.com/aurelia/skeleton-navigation/tree/1.1.2/skeleton-esnext-webpack what I believe to be the latest version is using the @easy web pack so those instructions are not valid. I'm attempting to see if I can figure out how to get the Froala editor to work with 1.1.2 if/once I figure it out I'll post it here, but if you already know what needs to be done that'd be great! Thanks --Steve

**Comment by sboyd** [comment]
@wjbarber3 thanks to[ this post](https://github.com/froala/aurelia-froala-editor/issues/32) I was able to get it working. @stefanneculai it may be worth updating the steps. I ended up just doing the following.

1)
Install plugin
npm install aurelia-froala-editor --save

2)
In your src/main.js or src/main.ts file add:
// Editor files.
import "froala-editor/js/froala_editor.pkgd.min";

3)
// Use the aurelia-froala-editor plugin.
aurelia.use.plugin('aurelia-froala-editor');

4)
In your .html include CSS files and Froala Editor component:
<require from="froala-editor/css/froala_editor.pkgd.min.css"></require>
<require from="froala-editor/css/froala_style.min.css"></require>

<froala-editor></froala-editor>

5)
In your package.json, add:

 ```
 "aurelia": {
    "build": {
      "resources": [
        "aurelia-froala-editor/froala-editor"
      ]
    }
  }

```
6)
Run application
npm run start

**Comment by stefanneculai** [comment]
Thanks @sboyd we're going to check it and add that to docs.

**Comment by wzrdtales** [comment]
same problem when using pnpm
